---
- name: Compare JSON files
  hosts: localhost
  gather_facts: false
  vars:
    source_hostname: "{{ source_hostname }}"
    target_hostname: "{{ target_hostname }}"
    source_json: "system_info_outputs/ec2_{{ source_hostname }}.json"
    target_json: "system_info_outputs/ec2_{{ target_hostname }}.json"

  tasks:
    - name: Ensure compare_json.py is present
      copy:
        src: compare_json.py
        dest: /tmp/compare_json.py
        mode: '0755'

    - name: Run compare_json.py with provided JSON files
      command: python3 /tmp/compare_json.py "{{ source_json }}" "{{ target_json }}"
      register: compare_result
      ignore_errors: true

    - name: Display comparison result
      debug:
        var: compare_result.stdout
