---
- name: Gather system information
  hosts: all
  become: false
  vars:
    dest_file: /tmp/system_info.txt
    local_output_dir: ./system_info_outputs
    local_file_path: "{{ local_output_dir }}/system_info_{{ inventory_hostname }}.txt"
    local_json_file_path: "{{ local_output_dir }}/system_info_{{ inventory_hostname }}.json"

  tasks:
    - name: Ensure local output directory exists
      delegate_to: localhost
      file:
        path: "{{ playbook_dir }}/{{ local_output_dir }}"
        state: directory
      become: false

    - name: Copy command.sh to /tmp/ on remote machine
      copy:
        src: ./command.sh
        dest: /tmp/command.sh
        mode: '0755'
      become: true

    - name: Execute command.sh
      shell: /tmp/command.sh
      register: result
      become: true

    - name: Fetch system_info.txt to local machine
      fetch:
        src: "{{ dest_file }}"
        dest: "{{ local_file_path }}"
        flat: yes

    - name: Print local_file_path
      delegate_to: localhost
      debug:
        msg: "local_file_path: {{ playbook_dir }}/{{ local_output_dir }}/system_info_{{ inventory_hostname }}.txt"

    - name: Print content of local_file_path
      delegate_to: localhost
      command: cat "{{ playbook_dir }}/{{ local_output_dir }}/system_info_{{ inventory_hostname }}.txt"
      register: file_content
      ignore_errors: true

    - name: Show content
      delegate_to: localhost
      debug:
        msg: "{{ file_content.stdout }}"
      when: file_content.rc == 0

    - name: Convert TXT to JSON
      delegate_to: localhost
      shell: |
        for file in {{ playbook_dir }}/{{ local_output_dir }}/*.txt; do
          python3 extract_system_info.py "$file" "{{local_json_file_path}}"
        done

    # print local_json_file_path and content
    - name: Print local_json_file_path
      delegate_to: localhost
      debug:
        msg: "local_json_file_path: {{ playbook_dir }}/{{ local_output_dir }}/system_info_{{ inventory_hostname }}.json"

    - name: Install required Python module json_dict_diff
      delegate_to: localhost
      shell: |
        pip3 install json_dict_diff

    - name: Ensure the directory structure exists locally
      delegate_to: localhost
      file:
        path: "{{ local_output_dir }}/ec2"
        state: directory

    - name: Fetch TXT file to local machine
      fetch:
        src: "{{ local_file_path }}"
        dest: "{{ playbook_dir }}/{{ local_output_dir }}/ec2/"
        flat: yes

    - name: Fetch JSON file to local machine
      fetch:
        src: "{{ local_json_file_path }}"
        dest: "{{ playbook_dir }}/{{ local_output_dir }}/ec2/"
        flat: yes

