---
- name: Gather system information
  hosts: all
  become: false
  vars:
    dest_file: /tmp/system_info.txt
    local_output_dir: ./system_info_outputs
    local_file_path: "{{ local_output_dir }}/system_info_{{ inventory_hostname }}.txt"
    local_json_file_path: "{{ local_output_dir }}/system_info_{{ inventory_hostname }}.json"
#adding new variables
    # source_host: 13.201.222.231         # Replace with actual hostname
    # target_host: 13.232.230.153         # Replace with actual hostname
    # source_json_path: "{{ playbook_dir }}/{{ local_output_dir }}/system_info_{{ source_host }}.json"
    # target_json_path: "{{ playbook_dir }}/{{ local_output_dir }}/system_info_{{ target_host }}.json"

  tasks:
    - name: Ensure local output directory exists
      delegate_to: localhost
      file:
        path: "{{ playbook_dir }}/{{ local_output_dir }}"
        state: directory
      become: false

    - name: Copy command.sh to /tmp/ on remote machine
      copy:
        src: ./command.sh
        dest: /tmp/command.sh
        mode: '0755'
      become: true

    - name: Execute command.sh
      shell: /tmp/command.sh
      register: result
      become: true

    # - name: Save the system information to a file
    #   copy:
    #     content: "{{ result.stdout }}"
    #     dest: "{{ dest_file }}"

    - name: Fetch system_info.txt to local machine
      fetch:
        src: "{{ dest_file }}"
        dest: "{{ local_file_path }}"
        flat: yes

    - name: Convert TXT to JSON
      delegate_to: localhost
      shell: |
        for file in {{ playbook_dir }}/{{ local_output_dir }}/*.txt; do
          python3 extract_system_info.py "$file" "{{local_json_file_path}}"
        done

    - name: Install required Python module json_dict_diff
      delegate_to: localhost
      shell: |
        pip3 install json_dict_diff

  ## testing comparison code
    # - name: Compare JSON configuration files
    #   delegate_to: localhost
    #   shell: |
    #       python3 compare_json.py \
    #         --src-dir "{{ playbook_dir }}/outputs/json" \
    #         --output-file "{{ playbook_dir }}/outputs/comparison_results.json"


    # - name: Compare two JSON files on the runner and show mismatches
    #   shell: |
    #     python3 compare_json.py "{{ source_json_path }}" "{{ target_json_path }}"
    #   register: compare_output
    #   ignore_errors: yes

    # - name: Show comparison results
    #   debug:
    #     var: compare_output.stdout

