name: Ansible EC2 System Info

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger
jobs:
  collect-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible python3

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip

      - name: Set permissions for the key
        run: chmod 600 infra/ubuntukey.pem

      - name: Start SSH Agent and add key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add infra/ubuntukey.pem

      # - name: Set up SSH
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          cp infra/ubuntukey.pem ~/.ssh/ubuntukey.pem
          chmod 600 ~/.ssh/ubuntukey.pem

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory.ini ec2_playbook.yml

      - name: Run Compare JSON Playbook
        run: |
          ansible-playbook compare_json_playbook.yaml -e "source_hostname=65.1.147.138 target_hostname=13.203.222.18"

      - name: Upload system information artifacts
        uses: actions/upload-artifact@v4
        with:
          name: system-info-outputs
          path: ./system_info_outputs/
          retention-days: 30

      # - name: Download system information artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: system-info-outputs
      #     path: ./downloaded_artifacts
