name: Ansible EC2 System Info

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger
jobs:
  collect-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible python3

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          import json
          import sys
          from json_dict_diff import diff  # Ensure you have installed this library

      - name: Set permissions for the key
        run: chmod 600 infra/ubuntukey.pem

      - name: Start SSH Agent and add key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add infra/ubuntukey.pem

      # - name: Set up SSH
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          cp infra/ubuntukey.pem ~/.ssh/ubuntukey.pem
          chmod 600 ~/.ssh/ubuntukey.pem

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory.ini playbook.yml
